FROM python:3.12-slim

WORKDIR /app

# Install deps
COPY monitoring_api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy Flask app
COPY monitoring_api /app/monitoring_api

ENV PYTHONPATH=/app
ENV PORT=8080

EXPOSE 8080

CMD ["python", "-m", "monitoring_api.app"]
